[build]
    command = "cd ../../ && npm run build && npm run build --workspace locale-router-static"
    publish = "build"
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 200
  force = true